const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const { sendEmail } = require('./emailService');

// Ensure invoices directory exists
const invoicesDir = path.join(__dirname, '../invoices');
if (!fs.existsSync(invoicesDir)) {
  fs.mkdirSync(invoicesDir, { recursive: true });
}

/**
 * Generate PDF invoice
 * @param {Object} invoiceData - Invoice data containing user, course, payment info
 * @returns {Promise<string>} - Path to generated PDF file
 */
const generateInvoice = async (invoiceData) => {
  return new Promise((resolve, reject) => {
    const {
      invoiceNumber,
      user,
      course,
      payment,
      paymentMethod,
      date
    } = invoiceData;

    // Create a new PDF document
    const doc = new PDFDocument({
      size: 'A4',
      margin: 50
    });

    // Generate filename
    const filename = `invoice_${invoiceNumber}.pdf`;
    const filepath = path.join(invoicesDir, filename);
    const stream = fs.createWriteStream(filepath);

    doc.pipe(stream);

    // Header - Company Name
    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .text('WEBHOC', 50, 50);

    doc
      .fontSize(10)
      .font('Helvetica')
      .text('Online Learning Platform', 50, 78);

    // Invoice title and number
    doc
      .fontSize(16)
      .font('Helvetica-Bold')
      .text('INVOICE', 400, 50);

    doc
      .fontSize(10)
      .font('Helvetica')
      .text(`Invoice #: ${invoiceNumber}`, 400, 78)
      .text(`Date: ${date}`, 400, 95);

    // Divider line
    doc
      .moveTo(50, 120)
      .lineTo(545, 120)
      .stroke();

    // Bill To section
    doc
      .fontSize(11)
      .font('Helvetica-Bold')
      .text('BILL TO:', 50, 140);

    doc
      .fontSize(10)
      .font('Helvetica')
      .text(user.displayName || user.email, 50, 160)
      .text(user.email, 50, 177)
      .text(user.phone || '(Not provided)', 50, 194);

    // Course Details section
    doc
      .fontSize(11)
      .font('Helvetica-Bold')
      .text('COURSE:', 300, 140);

    doc
      .fontSize(10)
      .font('Helvetica')
      .text(course.title, 300, 160, { width: 245, align: 'left' })
      .text(`Instructor: ${course.instructorId?.displayName || 'Unknown'}`, 300, 194);

    // Divider line
    doc
      .moveTo(50, 230)
      .lineTo(545, 230)
      .stroke();

    // Invoice Items Table
    const tableTop = 250;
    const col1X = 50;
    const col2X = 350;
    const col3X = 450;
    const rowHeight = 25;

    // Table headers
    doc
      .fontSize(11)
      .font('Helvetica-Bold')
      .text('Description', col1X, tableTop)
      .text('Amount', col2X, tableTop)
      .text('Total', col3X, tableTop);

    // Divider under headers
    doc
      .moveTo(50, tableTop + 20)
      .lineTo(545, tableTop + 20)
      .stroke();

    // Table row - Course
    const amountUSD = (payment.amountCents / 100).toFixed(2);
    doc
      .fontSize(10)
      .font('Helvetica')
      .text('Course Enrollment', col1X, tableTop + 30)
      .text(`$${amountUSD}`, col2X, tableTop + 30)
      .text(`$${amountUSD}`, col3X, tableTop + 30);

    // Subtotal row
    const subtotalY = tableTop + 70;
    doc
      .moveTo(50, subtotalY)
      .lineTo(545, subtotalY)
      .stroke();

    doc
      .fontSize(10)
      .font('Helvetica-Bold')
      .text('SUBTOTAL:', col2X, subtotalY + 10)
      .text(`$${amountUSD}`, col3X, subtotalY + 10);

    // Tax row (0% for now)
    doc
      .fontSize(10)
      .font('Helvetica')
      .text('Tax (0%):', col2X, subtotalY + 30)
      .text('$0.00', col3X, subtotalY + 30);

    // Total row
    const totalY = subtotalY + 50;
    doc
      .moveTo(50, totalY)
      .lineTo(545, totalY)
      .stroke();

    doc
      .fontSize(12)
      .font('Helvetica-Bold')
      .text('TOTAL:', col2X, totalY + 10)
      .text(`$${amountUSD}`, col3X, totalY + 10);

    // Payment details section
    const paymentY = totalY + 60;
    doc
      .fontSize(11)
      .font('Helvetica-Bold')
      .text('PAYMENT METHOD:', 50, paymentY);

    doc
      .fontSize(10)
      .font('Helvetica')
      .text(`Method: ${paymentMethod === 'stripe' ? 'Stripe (Credit Card)' : 'PayPal'}`, 50, paymentY + 20)
      .text(`Transaction ID: ${payment.transactionId}`, 50, paymentY + 37)
      .text(`Payment Status: ${payment.status.toUpperCase()}`, 50, paymentY + 54)
      .text(`Payment Date: ${date}`, 50, paymentY + 71);

    // Footer section
    const footerY = 720;
    doc
      .moveTo(50, footerY)
      .lineTo(545, footerY)
      .stroke();

    doc
      .fontSize(9)
      .font('Helvetica')
      .fillColor('#666666')
      .text('Thank you for your purchase!', 50, footerY + 15, { align: 'center', width: 495 })
      .text('For support, please contact: support@webhoc.com | Phone: 1-800-WEBHOC-1', 50, footerY + 35, { align: 'center', width: 495 })
      .text('This invoice was automatically generated by WEBHOC Learning Platform', 50, footerY + 50, { align: 'center', width: 495 });

    // End document
    doc.end();

    // Wait for file to be written
    stream.on('finish', () => {
      resolve(filepath);
    });

    stream.on('error', (err) => {
      reject(err);
    });

    doc.on('error', (err) => {
      reject(err);
    });
  });
};

/**
 * Send invoice via email
 * @param {Object} invoiceEmailData - Data for sending invoice email
 */
const sendInvoiceEmail = async (invoiceEmailData) => {
  const {
    userEmail,
    userName,
    courseName,
    invoiceNumber,
    invoicePath,
    amountUSD
  } = invoiceEmailData;

  const emailContent = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center;">
        <h1 style="margin: 0;">Invoice Received</h1>
      </div>
      
      <div style="padding: 30px; background: #f9f9f9;">
        <p style="font-size: 16px; color: #333;">Hi ${userName},</p>
        
        <p style="font-size: 14px; color: #666; line-height: 1.6;">
          Thank you for your purchase! Your invoice for <strong>${courseName}</strong> is attached below.
        </p>
        
        <div style="background: white; border-left: 4px solid #667eea; padding: 20px; margin: 20px 0;">
          <p style="margin: 10px 0;"><strong>Invoice Number:</strong> ${invoiceNumber}</p>
          <p style="margin: 10px 0;"><strong>Course:</strong> ${courseName}</p>
          <p style="margin: 10px 0;"><strong>Amount Paid:</strong> $${amountUSD}</p>
          <p style="margin: 10px 0;"><strong>Status:</strong> <span style="color: #28a745;">✓ Payment Confirmed</span></p>
        </div>
        
        <p style="font-size: 14px; color: #666; line-height: 1.6;">
          You now have full access to the course. Start learning immediately by logging into your WEBHOC account.
        </p>
        
        <div style="text-align: center; margin: 30px 0;">
          <a href="${process.env.CLIENT_URL}/dashboard" style="background: #667eea; color: white; padding: 12px 30px; text-decoration: none; border-radius: 5px; display: inline-block;">
            Go to Dashboard
          </a>
        </div>
        
        <hr style="border: none; border-top: 1px solid #ddd; margin: 30px 0;">
        
        <p style="font-size: 12px; color: #999; text-align: center; margin: 10px 0;">
          Questions? Contact us at <a href="mailto:support@webhoc.com" style="color: #667eea; text-decoration: none;">support@webhoc.com</a>
        </p>
      </div>
    </div>
  `;

  await sendEmail({
    to: userEmail,
    subject: `Invoice #${invoiceNumber} - ${courseName}`,
    html: emailContent,
    attachments: [
      {
        filename: `invoice_${invoiceNumber}.pdf`,
        path: invoicePath,
        contentType: 'application/pdf'
      }
    ]
  });
};

module.exports = {
  generateInvoice,
  sendInvoiceEmail
};
